# Generated by Django 5.0.9 on 2026-07-04 12:11

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStockLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('change_amount', models.DecimalField(decimal_places=3, help_text='Musbat qiymat — kirim; manfiy qiymat — chiqim.', max_digits=12, verbose_name="O'zgarish miqdori")),
                ('reason', models.CharField(choices=[('usage', 'Sarflash'), ('restock', "To'ldirish"), ('adjustment', 'Tuzatish')], max_length=20, verbose_name='Sabab')),
                ('resulting_quantity', models.DecimalField(decimal_places=3, help_text='Ushbu yozuvdan keyingi ombordagi miqdor — audit uchun snapshot.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Yakuniy zaxira')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Zaxira jurnali',
                'verbose_name_plural': 'Zaxira jurnallari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Sarflangan miqdor')),
            ],
            options={
                'verbose_name': 'Material sarflash',
                'verbose_name_plural': 'Material sarflashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMaterial',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(db_index=True, help_text="Material nomi, masalan: 'Filtek Z250', 'Endo fayli #25'.", max_length=150, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('gram', 'Gramm'), ('piece', 'Dona'), ('ml', 'Millilitr')], default='piece', max_length=10, verbose_name="O'lchov birligi")),
                ('quantity_in_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Joriy zaxira — sarflash signali orqali kamayadi.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Ombordagi miqdor')),
                ('minimum_threshold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Zaxira shu qiymatga tushganda bosh shifokorga ogohlantirish yuboriladi.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Minimum chegara')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text="Ixtiyoriy — komissiya 'from_net' asosda hisoblanganda material xarajati sifatida qo'llaniladi.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Birlik narxi')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izohlar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Material',
                'verbose_name_plural': 'historical Materiallar',
                'db_table': 'inventory_material_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(help_text="Material nomi, masalan: 'Filtek Z250', 'Endo fayli #25'.", max_length=150, unique=True, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('gram', 'Gramm'), ('piece', 'Dona'), ('ml', 'Millilitr')], default='piece', max_length=10, verbose_name="O'lchov birligi")),
                ('quantity_in_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Joriy zaxira — sarflash signali orqali kamayadi.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Ombordagi miqdor')),
                ('minimum_threshold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Zaxira shu qiymatga tushganda bosh shifokorga ogohlantirish yuboriladi.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Minimum chegara')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text="Ixtiyoriy — komissiya 'from_net' asosda hisoblanganda material xarajati sifatida qo'llaniladi.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Birlik narxi')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izohlar')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='inv_material_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('quantity_in_stock__gte', 0)), name='inventory_material_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('minimum_threshold__gte', 0)), name='inventory_material_threshold_non_negative'),
        ),
        migrations.AddField(
            model_name='materialstocklog',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', related_query_name='stock_log', to='inventory.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='materialstocklog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs_performed', to=settings.AUTH_USER_MODEL, verbose_name='Bajargan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='materialstocklog',
            name='related_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', related_query_name='stock_log', to='treatments.treatment', verbose_name="Bog'liq davolash"),
        ),
        migrations.AddField(
            model_name='materialusage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', related_query_name='usage', to='inventory.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='materialusage',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_usages_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Yozgan foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='materialusage',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', related_query_name='material_usage', to='treatments.treatment', verbose_name='Davolash'),
        ),
        migrations.AddField(
            model_name='materialstocklog',
            name='related_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', related_query_name='stock_log', to='inventory.materialusage', verbose_name="Bog'liq sarflash"),
        ),
        migrations.AddIndex(
            model_name='materialusage',
            index=models.Index(fields=['treatment'], name='inv_usage_treatment_idx'),
        ),
        migrations.AddIndex(
            model_name='materialusage',
            index=models.Index(fields=['material'], name='inv_usage_material_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialusage',
            constraint=models.CheckConstraint(check=models.Q(('quantity_used__gt', 0)), name='inventory_usage_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='materialstocklog',
            index=models.Index(fields=['material', '-created_at'], name='inv_log_material_idx'),
        ),
        migrations.AddIndex(
            model_name='materialstocklog',
            index=models.Index(fields=['reason'], name='inv_log_reason_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialstocklog',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('reason', 'usage'), ('change_amount__lt', 0)), models.Q(('reason', 'restock'), ('change_amount__gt', 0)), ('reason', 'adjustment'), _connector='OR'), name='inv_stock_log_reason_sign_consistent'),
        ),
    ]
