# Generated by Django 5.2.17 on 2026-08-15 07:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_timeoff_user_alter_workinghours_user'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureBOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('default_quantity', models.DecimalField(decimal_places=3, help_text='Ushbu muolaja uchun odatda sarflanadigan miqdor.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Standart miqdor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_boms', related_query_name='procedure_bom', to='inventory.material', verbose_name='Material')),
                ('procedure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', related_query_name='bom', to='doctors.proceduretype', verbose_name='Muolaja turi')),
            ],
            options={
                'verbose_name': 'Muolaja texkartasi',
                'verbose_name_plural': 'Muolaja texkartalari',
                'ordering': ['procedure_type', 'material'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('procedure_type', 'material'), name='inv_procedurebom_unique_active'), models.CheckConstraint(condition=models.Q(('default_quantity__gt', 0)), name='inv_procedurebom_qty_positive')],
            },
        ),
    ]
