# Generated by Django 5.2.17 on 2026-09-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_procedurebom'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaterial',
            name='batch_number',
            field=models.CharField(blank=True, default='', help_text='Ishlab chiqaruvchi partiya raqami.', max_length=100, verbose_name='Partiya / Lot raqami'),
        ),
        migrations.AddField(
            model_name='historicalmaterial',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Materialning amal qilish muddati.', null=True, verbose_name='Yaroqlilik muddati'),
        ),
        migrations.AddField(
            model_name='material',
            name='batch_number',
            field=models.CharField(blank=True, default='', help_text='Ishlab chiqaruvchi partiya raqami.', max_length=100, verbose_name='Partiya / Lot raqami'),
        ),
        migrations.AddField(
            model_name='material',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Materialning amal qilish muddati.', null=True, verbose_name='Yaroqlilik muddati'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['expiry_date'], name='inv_material_expiry_idx'),
        ),
    ]
