# Generated by Django 5.0.9 on 2026-07-04 09:04

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import re
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Xalqaro formatda, masalan +998901234567.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami xalqaro formatda bo'lishi kerak (masalan, +998901234567).", regex=re.compile('^\\+?[0-9]{7,15}$'))], verbose_name='Telefon raqami')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('role', models.CharField(choices=[('bosh_shifokor', 'Bosh shifokor'), ('doctor', 'Shifokor'), ('administrator', 'Administrator')], default='administrator', max_length=20, verbose_name='Roli')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram chat ID')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA yoqilgan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, help_text='Django admin panelga kirish uchun.', verbose_name='Xodim (admin panel)')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan sana")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi kirish')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, verbose_name='Kod')),
                ('purpose', models.CharField(choices=[('login', 'Kirish'), ('password_reset', 'Parolni tiklash')], default='login', max_length=20, verbose_name='Maqsad')),
                ('expires_at', models.DateTimeField(default=apps.accounts.models._default_otp_expiry, verbose_name='Amal qilish muddati')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'OTP kod',
                'verbose_name_plural': 'OTP kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_otp_lookup_idx'),
        ),
    ]
