# Generated by Django 5.2.17 on 2026-09-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('inventory.low_stock', 'Zaxira kam qoldi'), ('appointments.reminder_1d', 'Navbat eslatmasi (1 kun)'), ('appointments.reminder_2h', 'Navbat eslatmasi (2 soat)'), ('appointments.cancelled', 'Navbat bekor qilindi'), ('prescriptions.sent', 'Retsept yuborildi'), ('payments.received', "To'lov qabul qilindi"), ('finance.expense_created', 'Xarajat kiritildi'), ('treatments.completed', 'Muolaja yakunlandi'), ('patients.followup_invite', 'Profilaktik taklif'), ('patients.new', 'Yangi bemor'), ('ratings.milestone', 'Reyting yutugi'), ('generic', 'Umumiy')], default='generic', max_length=64, verbose_name='Turi'),
        ),
    ]
