# Generated by Django 5.2.17 on 2026-08-05 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPermissionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('role', models.CharField(choices=[('doctor', 'Shifokor'), ('administrator', 'Administrator')], max_length=20, unique=True, verbose_name='Rol')),
                ('can_view_inventory_costs', models.BooleanField(default=False, verbose_name="Ombor narxlarini ko'rish")),
                ('can_view_financial_reports', models.BooleanField(default=False, verbose_name="Moliyaviy hisobotlarni ko'rish")),
                ('can_view_other_doctors_stats', models.BooleanField(default=False, verbose_name="Boshqa shifokorlar statistikasini ko'rish")),
                ('can_view_all_patients', models.BooleanField(default=False, verbose_name="Barcha bemorlar ma'lumotini ko'rish")),
            ],
            options={
                'verbose_name': 'AI Ruxsat Sozlamasi',
                'verbose_name_plural': 'AI Ruxsat Sozlamalari',
            },
        ),
    ]
