# Generated by Django 5.0.9 on 2026-07-04 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('slug', models.SlugField(help_text="Barqaror identifikator, masalan 'top_doctor_month'.", max_length=64, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, default='', help_text="Frontend'da ko'rsatiladigan ikon nomi (masalan 'trophy').", max_length=100, verbose_name='Ikon')),
            ],
            options={
                'verbose_name': 'Nishon',
                'verbose_name_plural': 'Nishonlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('points', models.IntegerField(help_text="Ijobiy — ball qo'shildi; manfiy — ball ayirildi.", verbose_name='Ballar')),
                ('reason', models.CharField(choices=[('new_patient', 'Yangi bemor'), ('treatment_completed', 'Davolash yakunlandi'), ('photo_uploaded', 'Rasm yuklandi'), ('activity_streak', 'Faollik ketma-ketligi'), ('adjustment', "Qo'lda tuzatish")], max_length=30, verbose_name='Sabab')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', related_query_name='score_log', to='doctors.doctorprofile', verbose_name='Shifokor')),
                ('related_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_logs', related_query_name='score_log', to='patients.patient', verbose_name="Bog'liq bemor")),
                ('related_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_logs', related_query_name='score_log', to='treatments.treatment', verbose_name="Bog'liq davolash")),
            ],
            options={
                'verbose_name': 'Ball yozuvi',
                'verbose_name_plural': 'Ball yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('period', models.CharField(help_text="Masalan '2026-07' — oylik reyting davri.", max_length=16, verbose_name='Davri')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan sana')),
                ('total_points', models.IntegerField(default=0, help_text='Nishon berilgan paytdagi umumiy ballar (audit uchun snapshot).', verbose_name="Davr yakuni bo'yicha ballar")),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', related_query_name='award', to='ratings.badge', verbose_name='Nishon')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', related_query_name='badge', to='doctors.doctorprofile', verbose_name='Shifokor')),
            ],
            options={
                'verbose_name': 'Shifokor nishoni',
                'verbose_name_plural': 'Shifokor nishonlari',
                'ordering': ['-awarded_at'],
                'indexes': [models.Index(fields=['doctor', '-awarded_at'], name='ratings_db_doctor_idx'), models.Index(fields=['period'], name='ratings_db_period_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='doctorbadge',
            constraint=models.UniqueConstraint(fields=('doctor', 'badge', 'period'), name='ratings_doctorbadge_unique_per_period'),
        ),
        migrations.AddIndex(
            model_name='scorelog',
            index=models.Index(fields=['doctor', '-created_at'], name='ratings_log_doctor_idx'),
        ),
        migrations.AddIndex(
            model_name='scorelog',
            index=models.Index(fields=['reason'], name='ratings_log_reason_idx'),
        ),
        migrations.AddIndex(
            model_name='scorelog',
            index=models.Index(fields=['created_at'], name='ratings_log_created_idx'),
        ),
    ]
