# Generated by Django 5.2.17 on 2026-08-17 08:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_timeoff_user_alter_workinghours_user'),
        ('patients', '0001_initial'),
        ('ratings', '0001_initial'),
        ('treatments', '0004_historicaltreatment_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('rating', models.IntegerField(help_text="1 dan 5 gacha bo'lgan baho", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baho')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reviews', to='doctors.doctorprofile', verbose_name='Shifokor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reviews', to='patients.patient', verbose_name='Bemor')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_reviews', to='treatments.treatment', verbose_name='Davolash')),
            ],
            options={
                'verbose_name': 'Bemor izohi',
                'verbose_name_plural': 'Bemor izohlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', '-created_at'], name='ratings_review_doctor_idx')],
            },
        ),
    ]
