# Generated by Django 5.0.9 on 2026-07-04 10:13

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalToothRecord',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('tooth_number', models.PositiveSmallIntegerField(help_text='FDI tish raqamlari: 11–18, 21–28, 31–38, 41–48 (jami 32 ta doimiy tish).', validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(48)], verbose_name='Tish raqami (FDI)')),
                ('procedure', models.CharField(choices=[('filling', 'Plomba'), ('root_canal', 'Kanal davolash'), ('extraction', 'Olib tashlash'), ('crown', 'Koronka'), ('implant', 'Implant'), ('cleaning', 'Tozalash'), ('whitening', 'Oqartirish')], max_length=20, verbose_name='Muolaja')),
                ('status', models.CharField(choices=[('healthy', "Sog'lom"), ('treated', 'Davolangan'), ('missing', "Yo'q / olib tashlangan"), ('planned', 'Rejalashtirilgan')], default='planned', max_length=10, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izohlar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='tooth_record', to='treatments.treatment', verbose_name='Davolash')),
            ],
            options={
                'verbose_name': 'historical Tish yozuvi',
                'verbose_name_plural': 'historical Tish yozuvlari',
                'db_table': 'odontogram_toothrecord_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('tooth_number', models.PositiveSmallIntegerField(help_text='FDI tish raqamlari: 11–18, 21–28, 31–38, 41–48 (jami 32 ta doimiy tish).', validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(48)], verbose_name='Tish raqami (FDI)')),
                ('procedure', models.CharField(choices=[('filling', 'Plomba'), ('root_canal', 'Kanal davolash'), ('extraction', 'Olib tashlash'), ('crown', 'Koronka'), ('implant', 'Implant'), ('cleaning', 'Tozalash'), ('whitening', 'Oqartirish')], max_length=20, verbose_name='Muolaja')),
                ('status', models.CharField(choices=[('healthy', "Sog'lom"), ('treated', 'Davolangan'), ('missing', "Yo'q / olib tashlangan"), ('planned', 'Rejalashtirilgan')], default='planned', max_length=10, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izohlar')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', related_query_name='tooth_record', to='treatments.treatment', verbose_name='Davolash')),
            ],
            options={
                'verbose_name': 'Tish yozuvi',
                'verbose_name_plural': 'Tish yozuvlari',
                'ordering': ['tooth_number', '-created_at'],
                'indexes': [models.Index(fields=['treatment', 'tooth_number'], name='tr_tr_tn_idx'), models.Index(fields=['status'], name='tr_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='toothrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('tooth_number__gte', 11), ('tooth_number__lte', 18)), models.Q(('tooth_number__gte', 21), ('tooth_number__lte', 28)), models.Q(('tooth_number__gte', 31), ('tooth_number__lte', 38)), models.Q(('tooth_number__gte', 41), ('tooth_number__lte', 48)), _connector='OR'), name='odontogram_toothrecord_fdi_range'),
        ),
        migrations.AddConstraint(
            model_name='toothrecord',
            constraint=models.UniqueConstraint(fields=('treatment', 'tooth_number'), name='odontogram_toothrecord_unique_per_treatment'),
        ),
    ]
