# Generated by Django 5.2.17 on 2026-09-04 05:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontogram', '0001_initial'),
        ('patients', '0002_historicalpatient_allergies_and_more'),
        ('treatments', '0004_historicaltreatment_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='toothrecord',
            name='odontogram_toothrecord_fdi_range',
        ),
        migrations.RemoveConstraint(
            model_name='toothrecord',
            name='odontogram_toothrecord_unique_per_treatment',
        ),
        migrations.AddField(
            model_name='historicaltoothrecord',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='tooth_record', to='patients.patient', verbose_name='Bemor'),
        ),
        migrations.AddField(
            model_name='historicaltoothrecord',
            name='surfaces',
            field=models.JSONField(blank=True, default=list, help_text='Tishning shikastlangan/davolangan yuzalari: O, M, D, V, L.', verbose_name='Tish sirtlari'),
        ),
        migrations.AddField(
            model_name='toothrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', related_query_name='tooth_record', to='patients.patient', verbose_name='Bemor'),
        ),
        migrations.AddField(
            model_name='toothrecord',
            name='surfaces',
            field=models.JSONField(blank=True, default=list, help_text='Tishning shikastlangan/davolangan yuzalari: O, M, D, V, L.', verbose_name='Tish sirtlari'),
        ),
        migrations.AlterField(
            model_name='historicaltoothrecord',
            name='procedure',
            field=models.CharField(choices=[('filling', 'Plomba'), ('root_canal', 'Kanal davolash'), ('extraction', 'Olib tashlash'), ('crown', 'Koronka'), ('implant', 'Implant'), ('cleaning', 'Tozalash'), ('whitening', 'Oqartirish'), ('other', 'Boshqa')], max_length=20, verbose_name='Muolaja'),
        ),
        migrations.AlterField(
            model_name='historicaltoothrecord',
            name='tooth_number',
            field=models.PositiveSmallIntegerField(help_text='FDI tish raqamlari: Doimiy 11–48 (32 ta) yoki Sut tishlari 51–85 (20 ta).', validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(85)], verbose_name='Tish raqami (FDI)'),
        ),
        migrations.AlterField(
            model_name='toothrecord',
            name='procedure',
            field=models.CharField(choices=[('filling', 'Plomba'), ('root_canal', 'Kanal davolash'), ('extraction', 'Olib tashlash'), ('crown', 'Koronka'), ('implant', 'Implant'), ('cleaning', 'Tozalash'), ('whitening', 'Oqartirish'), ('other', 'Boshqa')], max_length=20, verbose_name='Muolaja'),
        ),
        migrations.AlterField(
            model_name='toothrecord',
            name='tooth_number',
            field=models.PositiveSmallIntegerField(help_text='FDI tish raqamlari: Doimiy 11–48 (32 ta) yoki Sut tishlari 51–85 (20 ta).', validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(85)], verbose_name='Tish raqami (FDI)'),
        ),
        migrations.AlterField(
            model_name='toothrecord',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', related_query_name='tooth_record', to='treatments.treatment', verbose_name='Davolash'),
        ),
        migrations.AddIndex(
            model_name='toothrecord',
            index=models.Index(fields=['patient', 'tooth_number'], name='tr_pat_tn_idx'),
        ),
        migrations.AddConstraint(
            model_name='toothrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tooth_number__gte', 11), ('tooth_number__lte', 18)), models.Q(('tooth_number__gte', 21), ('tooth_number__lte', 28)), models.Q(('tooth_number__gte', 31), ('tooth_number__lte', 38)), models.Q(('tooth_number__gte', 41), ('tooth_number__lte', 48)), models.Q(('tooth_number__gte', 51), ('tooth_number__lte', 55)), models.Q(('tooth_number__gte', 61), ('tooth_number__lte', 65)), models.Q(('tooth_number__gte', 71), ('tooth_number__lte', 75)), models.Q(('tooth_number__gte', 81), ('tooth_number__lte', 85)), _connector='OR'), name='odontogram_toothrecord_fdi_range'),
        ),
    ]
