# Generated by Django 5.2.17 on 2026-08-12 04:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(default='DentaCRM Stomatologiya', max_length=255)),
                ('inn', models.CharField(blank=True, default='123456789', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='Toshkent sh., Yunusobod t.', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Klinika Sozlamalari',
                'verbose_name_plural': 'Klinika Sozlamalari',
            },
        ),
    ]
