# Generated by Django 5.2.17 on 2026-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clinicsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='phone',
            field=models.CharField(blank=True, default='+998 90 123 45 67', max_length=50, null=True),
        ),
    ]
