# Generated by Django 5.0.9 on 2026-07-04 12:34

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Miqdor')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('payme', 'Payme'), ('click', 'Click'), ('bank_transfer', "Bank o'tkazmasi")], default='cash', max_length=20, verbose_name="To'lov turi")),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='payment', to='patients.patient', verbose_name='Bemor')),
                ('received_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='payment_received', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan xodim')),
                ('treatment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='payment', to='treatments.treatment', verbose_name='Davolash')),
            ],
            options={
                'verbose_name': "historical To'lov",
                'verbose_name_plural': "historical To'lovlar",
                'db_table': 'payments_payment_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Miqdor')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('payme', 'Payme'), ('click', 'Click'), ('bank_transfer', "Bank o'tkazmasi")], default='cash', max_length=20, verbose_name="To'lov turi")),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', related_query_name='payment', to='patients.patient', verbose_name='Bemor')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', related_query_name='payment_received', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan xodim')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', related_query_name='payment', to='treatments.treatment', verbose_name='Davolash')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Komissiya miqdori')),
                ('rate', models.DecimalField(decimal_places=2, help_text="Hisoblash paytida qo'llanilgan foiz (0–100).", max_digits=5, verbose_name='Foiz')),
                ('basis', models.CharField(choices=[('from_total', 'Umumiy narxdan'), ('from_net', 'Sof daromaddan')], max_length=20, verbose_name='Asos')),
                ('base_amount', models.DecimalField(decimal_places=2, help_text="Foiz qo'llanilgan pul miqdori (from_total: narx, from_net: narx - material).", max_digits=12, verbose_name='Hisoblash bazasi')),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='from_net asosda ishlatilgan material xarajati. from_total uchun 0.', max_digits=12, verbose_name='Material xarajati')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Hisoblangan vaqti')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', related_query_name='commission', to='doctors.doctorprofile', verbose_name='Shifokor')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', related_query_name='commission', to='treatments.treatment', verbose_name='Davolash')),
            ],
            options={
                'verbose_name': 'Komissiya yozuvi',
                'verbose_name_plural': 'Komissiya yozuvlari',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['doctor', '-calculated_at'], name='comm_doctor_idx'), models.Index(fields=['treatment'], name='comm_treatment_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='commissionrecord',
            constraint=models.UniqueConstraint(fields=('doctor', 'treatment'), name='payments_commission_unique_per_doctor_treatment'),
        ),
        migrations.AddConstraint(
            model_name='commissionrecord',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='payments_commission_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='commissionrecord',
            constraint=models.CheckConstraint(check=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='payments_commission_rate_bounded'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['treatment', '-created_at'], name='pay_treatment_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', '-created_at'], name='pay_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='pay_method_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payments_payment_amount_positive'),
        ),
    ]
