# Generated by Django 5.0.9 on 2026-07-04 09:40

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone_number', models.CharField(help_text='Xalqaro formatda saqlanadi (masalan +998901234567).', max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqami xalqaro formatda bo'lishi kerak (masalan, +998901234567).", regex='^\\+?[0-9]{7,15}$')], verbose_name='Telefon raqami')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Manzil')),
                ('notes', models.TextField(blank=True, default='', help_text='Allergiya, surunkali kasalliklar va boshqa muhim tibbiy izohlar.', verbose_name='Eslatmalar')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, db_index=True, help_text='Bemorga eslatma va retseptni Telegram orqali yuborish uchun.', null=True, verbose_name='Telegram chat ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='patient_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Bemor',
                'verbose_name_plural': 'historical Bemorlar',
                'db_table': 'patients_patient_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone_number', models.CharField(help_text='Xalqaro formatda saqlanadi (masalan +998901234567).', max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqami xalqaro formatda bo'lishi kerak (masalan, +998901234567).", regex='^\\+?[0-9]{7,15}$')], verbose_name='Telefon raqami')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, null=True, verbose_name='Jinsi')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Manzil')),
                ('notes', models.TextField(blank=True, default='', help_text='Allergiya, surunkali kasalliklar va boshqa muhim tibbiy izohlar.', verbose_name='Eslatmalar')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, help_text='Bemorga eslatma va retseptni Telegram orqali yuborish uchun.', null=True, unique=True, verbose_name='Telegram chat ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients_created', related_query_name='patient_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='patients_name_idx'), models.Index(fields=['phone_number'], name='patients_phone_idx'), models.Index(django.db.models.functions.text.Lower('last_name'), name='patients_lname_ci_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('phone_number',), name='patients_patient_phone_unique_active'),
        ),
    ]
