# Generated by Django 5.2.17 on 2026-09-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='allergies',
            field=models.TextField(blank=True, default='', help_text='Dori, anesteziya yoki boshqa moddalarga allergik reaksiyalar.', verbose_name='Allergiyalar'),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Bemorning tug'ilgan sanasi (yosh va profilaktika uchun).", null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='blood_group',
            field=models.CharField(blank=True, default='', help_text='Masalan: I+, II+, III-, IV+', max_length=10, verbose_name='Qon guruhi'),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, default='', help_text='Dori, anesteziya yoki boshqa moddalarga allergik reaksiyalar.', verbose_name='Allergiyalar'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Bemorning tug'ilgan sanasi (yosh va profilaktika uchun).", null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, default='', help_text='Masalan: I+, II+, III-, IV+', max_length=10, verbose_name='Qon guruhi'),
        ),
    ]
