# Generated by Django 5.0.9 on 2026-07-04 10:03

import apps.treatments.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0002_appointment_exclusion_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTreatment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('diagnosis', models.CharField(blank=True, default='', max_length=500, verbose_name='Tashxis')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Narx')),
                ('payment_status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', "Qisman to'langan"), ('paid', "To'langan")], default='unpaid', max_length=10, verbose_name="To'lov holati")),
                ('stage', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlangan')], default='in_progress', max_length=20, verbose_name='Bosqichi')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('appointment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='treatment', to='scheduling.appointment', verbose_name='Navbat')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='treatment_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='treatment', to='departments.department', verbose_name="Bo'lim")),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='treatment', to='doctors.doctorprofile', verbose_name='Shifokor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='treatment', to='patients.patient', verbose_name='Bemor')),
                ('procedure_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='treatment', to='doctors.proceduretype', verbose_name='Muolaja turi')),
            ],
            options={
                'verbose_name': 'historical Davolash',
                'verbose_name_plural': 'historical Davolashlar',
                'db_table': 'treatments_treatment_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('diagnosis', models.CharField(blank=True, default='', max_length=500, verbose_name='Tashxis')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Narx')),
                ('payment_status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', "Qisman to'langan"), ('paid', "To'langan")], default='unpaid', max_length=10, verbose_name="To'lov holati")),
                ('stage', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlangan')], default='in_progress', max_length=20, verbose_name='Bosqichi')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', related_query_name='treatment', to='scheduling.appointment', verbose_name='Navbat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatments_created', related_query_name='treatment_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', related_query_name='treatment', to='departments.department', verbose_name="Bo'lim")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', related_query_name='treatment', to='doctors.doctorprofile', verbose_name='Shifokor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', related_query_name='treatment', to='patients.patient', verbose_name='Bemor')),
                ('procedure_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', related_query_name='treatment', to='doctors.proceduretype', verbose_name='Muolaja turi')),
            ],
            options={
                'verbose_name': 'Davolash',
                'verbose_name_plural': 'Davolashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('photo_type', models.CharField(choices=[('before', 'Davolashdan oldin'), ('after', 'Davolashdan keyin'), ('xray', 'Rentgen')], max_length=10, verbose_name='Rasm turi')),
                ('image', models.ImageField(max_length=500, upload_to=apps.treatments.models._treatment_photo_upload_to, verbose_name='Rasm')),
                ('thumbnail_path', models.CharField(blank=True, default='', help_text="T23 (Celery task) tomonidan generatsiya qilinadigan kichraytirilgan rasm yo'li. Bo'sh qoldirilsa asosiy rasm ko'rsatiladi.", max_length=500, verbose_name="Thumbnail yo'li")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='treatments.treatment', verbose_name='Davolash')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_photos_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Davolash rasmi',
                'verbose_name_plural': 'Davolash rasmlari',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['patient', '-created_at'], name='tr_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['doctor', '-created_at'], name='tr_doctor_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['payment_status'], name='tr_paystatus_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['stage'], name='tr_stage_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='treatments_treatment_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='treatmentphoto',
            index=models.Index(fields=['treatment', 'photo_type'], name='tp_treatment_type_idx'),
        ),
    ]
