# Generated by Django 5.0.9 on 2026-07-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="T23 (Celery task) tomonidan generatsiya qilingan 300px kichraytirilgan rasm. Bo'sh bo'lsa asosiy rasm ko'rsatiladi.", max_length=500, null=True, upload_to='treatments/thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='treatmentphoto',
            name='thumbnail_path',
            field=models.CharField(blank=True, default='', help_text="Thumbnail fayl yo'li (denormalizatsiya — API ni tez oqish uchun).", max_length=500, verbose_name="Thumbnail yo'li"),
        ),
    ]
