# Generated by Django 5.2.17 on 2026-08-07 12:38

import apps.treatments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_treatmentphoto_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentphoto',
            name='image',
            field=models.FileField(max_length=500, upload_to=apps.treatments.models._treatment_photo_upload_to, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='treatmentphoto',
            name='thumbnail',
            field=models.FileField(blank=True, help_text="T23 (Celery task) tomonidan generatsiya qilingan 300px kichraytirilgan rasm. Bo'sh bo'lsa asosiy rasm ko'rsatiladi.", max_length=500, null=True, upload_to='treatments/thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
