# Generated by Django 5.2.17 on 2026-08-11 09:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_alter_treatmentphoto_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltreatment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='approved', max_length=20, verbose_name='Tasdiqlash holati'),
        ),
        migrations.AddField(
            model_name='historicaltreatment',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Chegirma foizi'),
        ),
        migrations.AddField(
            model_name='historicaltreatment',
            name='discount_reason',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Chegirma sababi'),
        ),
        migrations.AddField(
            model_name='historicaltreatment',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Asl Narx'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='approved', max_length=20, verbose_name='Tasdiqlash holati'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Chegirma foizi'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='discount_reason',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Chegirma sababi'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Asl Narx'),
        ),
    ]
