# Generated by Django 5.2.17 on 2026-09-29 09:01

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_historicalproceduretype_price_per_surface_and_more'),
        ('patients', '0002_historicalpatient_allergies_and_more'),
        ('treatments', '0004_historicaltreatment_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='XKT-10 Kodi')),
                ('name_uz', models.CharField(max_length=300, verbose_name="Tashxis nomi (O'zbekcha)")),
                ('name_ru', models.CharField(blank=True, default='', max_length=300, verbose_name='Tashxis nomi (Ruscha)')),
                ('category', models.CharField(blank=True, default='', max_length=150, verbose_name='Kategoriya')),
                ('is_common', models.BooleanField(default=True, verbose_name="Ko'p uchraydigan")),
            ],
            options={
                'verbose_name': 'XKT-10 Tashxis',
                'verbose_name_plural': 'XKT-10 Tashxislar',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='historicaltreatment',
            name='icd_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='XKT-10 Kodi'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='icd_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='XKT-10 Kodi'),
        ),
        migrations.CreateModel(
            name='HistoricalTreatmentPlan',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('title', models.CharField(default='Kompleks davolash rejasi', max_length=250, verbose_name='Reja nomi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('proposed', 'Taklif qilingan'), ('accepted', 'Bemor qabul qilgan'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='proposed', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Klinik izohlar')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Chegirma foizi')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Tuzgan xodim')),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='treatment_plan', to='doctors.doctorprofile', verbose_name='Shifokor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='treatment_plan', to='patients.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'historical Davolash rejasi',
                'verbose_name_plural': 'historical Davolash rejalari',
                'db_table': 'treatments_treatmentplan_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicaltreatment',
            name='icd_diagnosis',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treatments.icd10diagnosis', verbose_name='XKT-10 Tashxis'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='icd_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='treatments.icd10diagnosis', verbose_name='XKT-10 Tashxis'),
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('title', models.CharField(default='Kompleks davolash rejasi', max_length=250, verbose_name='Reja nomi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('proposed', 'Taklif qilingan'), ('accepted', 'Bemor qabul qilgan'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='proposed', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Klinik izohlar')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Chegirma foizi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Tuzgan xodim')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', related_query_name='treatment_plan', to='doctors.doctorprofile', verbose_name='Shifokor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', related_query_name='treatment_plan', to='patients.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Davolash rejasi',
                'verbose_name_plural': 'Davolash rejalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('tooth_number', models.PositiveSmallIntegerField(blank=True, help_text="Ixtiyoriy: muayyan tishga tegishli bo'lsa (11-85).", null=True, verbose_name='Tish raqami (FDI)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Bosqich tartibi')),
                ('title', models.CharField(max_length=250, verbose_name='Bosqich / Muolaja nomi')),
                ('estimated_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxminiy narx')),
                ('status', models.CharField(choices=[('planned', 'Rejalashtirilgan'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='planned', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('completed_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items_completed', to='treatments.treatment', verbose_name='Bajarilgan davolash')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='treatments.treatmentplan', verbose_name='Davolash rejasi')),
                ('procedure_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='doctors.proceduretype', verbose_name='Muolaja turi')),
            ],
            options={
                'verbose_name': 'Davolash rejasi bandi',
                'verbose_name_plural': 'Davolash rejasi bandlari',
                'ordering': ['plan', 'order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='historicaltreatment',
            name='plan_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treatments.treatmentplanitem', verbose_name='Reja bandi'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_treatments', to='treatments.treatmentplanitem', verbose_name='Reja bandi'),
        ),
    ]
