# Generated by Django 5.0.9 on 2026-07-04 09:50

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAppointment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('scheduled_start', models.DateTimeField(verbose_name='Boshlanish')),
                ('scheduled_end', models.DateTimeField(verbose_name='Tugash')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('confirmed', 'Tasdiqlangan'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan'), ('no_show', 'Kelmadi')], default='scheduled', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, default='', help_text="Reseptsionist yozib qo'yadigan izohlar (masalan, sabab).", verbose_name='Izohlar')),
                ('reminder_1d_sent', models.BooleanField(default=False, verbose_name='1 kunlik eslatma yuborilgan')),
                ('reminder_2h_sent', models.BooleanField(default=False, verbose_name='2 soatlik eslatma yuborilgan')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='appointment_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='appointment', to='departments.department', verbose_name="Bo'lim")),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='appointment', to='doctors.doctorprofile', verbose_name='Shifokor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='appointment', to='patients.patient', verbose_name='Bemor')),
                ('procedure_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='appointment', to='doctors.proceduretype', verbose_name='Muolaja turi')),
            ],
            options={
                'verbose_name': 'historical Navbat',
                'verbose_name_plural': 'historical Navbatlar',
                'db_table': 'scheduling_appointment_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('scheduled_start', models.DateTimeField(verbose_name='Boshlanish')),
                ('scheduled_end', models.DateTimeField(verbose_name='Tugash')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('confirmed', 'Tasdiqlangan'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan'), ('no_show', 'Kelmadi')], default='scheduled', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, default='', help_text="Reseptsionist yozib qo'yadigan izohlar (masalan, sabab).", verbose_name='Izohlar')),
                ('reminder_1d_sent', models.BooleanField(default=False, verbose_name='1 kunlik eslatma yuborilgan')),
                ('reminder_2h_sent', models.BooleanField(default=False, verbose_name='2 soatlik eslatma yuborilgan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', related_query_name='appointment_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', related_query_name='appointment', to='departments.department', verbose_name="Bo'lim")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', related_query_name='appointment', to='doctors.doctorprofile', verbose_name='Shifokor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', related_query_name='appointment', to='patients.patient', verbose_name='Bemor')),
                ('procedure_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', related_query_name='appointment', to='doctors.proceduretype', verbose_name='Muolaja turi')),
            ],
            options={
                'verbose_name': 'Navbat',
                'verbose_name_plural': 'Navbatlar',
                'ordering': ['-scheduled_start'],
                'indexes': [models.Index(fields=['doctor', 'scheduled_start'], name='sched_appt_doc_start_idx'), models.Index(fields=['patient', 'scheduled_start'], name='sched_appt_pat_start_idx'), models.Index(fields=['status'], name='sched_appt_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('scheduled_start__lt', models.F('scheduled_end'))), name='scheduling_appointment_start_before_end'),
        ),
    ]
