# Generated by Django 5.0.9 on 2026-07-04 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('content', models.TextField(help_text="Retsept matni. Placeholderlar (masalan {patient_name}) qo'llab-quvvatlanadi va yaratish vaqtida almashtiriladi.", verbose_name='Matn')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_templates', related_query_name='prescription_template', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Retsept shabloni',
                'verbose_name_plural': 'Retsept shablonlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('content', models.TextField(help_text="Retsept matni — patientga yuboriladigan yakuniy versiya. Shablondan olingan bo'lsa ham, bu yerda mustaqil saqlanadi.", verbose_name='Matn')),
                ('sent_to_telegram_at', models.DateTimeField(blank=True, null=True, verbose_name='Telegram ga yuborilgan sana')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_created', related_query_name='prescription_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', related_query_name='prescription', to='treatments.treatment', verbose_name='Davolash')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', related_query_name='prescription', to='prescriptions.prescriptiontemplate', verbose_name='Shablon')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplate',
            index=models.Index(fields=['name'], name='pr_tpl_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescriptiontemplate',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='prescriptions_template_unique_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['treatment', '-created_at'], name='pr_tr_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['sent_to_telegram_at'], name='pr_sent_idx'),
        ),
    ]
