# Generated by Django 5.0.9 on 2026-07-04 09:22

import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDepartment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(help_text="Bo'lim nomi, masalan: Terapiya, Ortopediya, Xirurgiya.", max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, default='', help_text="Ixtiyoriy — bo'lim xizmatlari haqida qisqacha izoh.", verbose_name='Tavsif')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='department_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical Bo'lim",
                'verbose_name_plural': "historical Bo'limlar",
                'db_table': 'departments_department_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(help_text="Bo'lim nomi, masalan: Terapiya, Ortopediya, Xirurgiya.", max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, default='', help_text="Ixtiyoriy — bo'lim xizmatlari haqida qisqacha izoh.", verbose_name='Tavsif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments_created', related_query_name='department_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='departments_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True)), name='departments_department_name_ci_unique'),
        ),
    ]
