# Generated by Django 5.2.17 on 2026-08-11 09:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Ochilgan vaqti')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqti')),
                ('start_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Boshlang'ich qoldiq")),
                ('cash_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Naqd tushum')),
                ('card_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Karta/Plastik tushum')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('closed', 'Yopiq')], default='open', max_length=10, verbose_name='Holati')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan shaxs')),
            ],
            options={
                'verbose_name': 'Kassa Smenasi',
                'verbose_name_plural': 'Kassa Smenalari',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='cash_shift',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.cashshift', verbose_name='Kassa Smenasi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.cashshift', verbose_name='Kassa Smenasi'),
        ),
    ]
