# Generated by Django 5.2.17 on 2026-08-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cashshift_historicalpayment_cash_shift_and_more'),
        ('treatments', '0004_historicaltreatment_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', related_query_name='payment', to='treatments.treatment', verbose_name='Davolash'),
        ),
    ]
