# Generated by Django 5.2.17 on 2026-08-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='refund_status',
            field=models.CharField(choices=[('none', "Yo'q"), ('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='none', max_length=20, verbose_name='Qaytarish holati'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(choices=[('none', "Yo'q"), ('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='none', max_length=20, verbose_name='Qaytarish holati'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
    ]
