# Generated by Django 5.2.17 on 2026-08-15 08:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_historicalpayment_refund_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Toifa nomi')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Xarajat toifasi',
                'verbose_name_plural': 'Xarajat toifalari',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cashshift',
            name='card_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Karta xarajatlar'),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='cash_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Naqd xarajatlar'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('description', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('payme', 'Payme'), ('click', 'Click'), ('bank_transfer', "Bank o'tkazmasi")], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('cash_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='payments.cashshift', verbose_name='Smena')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan shaxs')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.expensecategory', verbose_name='Toifa')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-date'],
            },
        ),
    ]
