# Generated by Django 5.2.17 on 2026-08-15 11:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_timeoff_user_alter_workinghours_user'),
        ('payments', '0005_expensecategory_cashshift_card_expenses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="To'langan summa")),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('payme', 'Payme'), ('click', 'Click'), ('bank_transfer', "Bank o'tkazmasi")], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izoh')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('cash_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments', to='payments.cashshift', verbose_name='Kassa Smenasi')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='doctors.doctorprofile', verbose_name='Shifokor')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payment', to='payments.expense', verbose_name='Xarajat yozuvi')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_salaries', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan shaxs')),
            ],
            options={
                'verbose_name': "Ish haqi to'lovi",
                'verbose_name_plural': "Ish haqi to'lovlari",
                'ordering': ['-date'],
            },
        ),
    ]
