# Generated by Django 5.2.17 on 2026-08-12 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_backfill_doctor_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['user__last_name', 'weekday', 'start_time'], 'verbose_name': 'Ish soati', 'verbose_name_plural': 'Ish soatlari'},
        ),
        migrations.RemoveConstraint(
            model_name='workinghours',
            name='doctors_workinghours_unique_slot',
        ),
        migrations.RemoveIndex(
            model_name='timeoff',
            name='doctors_timeoff_range_idx',
        ),
        migrations.RemoveIndex(
            model_name='workinghours',
            name='doctors_wh_by_day_idx',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='doctor',
        ),
        migrations.AddField(
            model_name='timeoff',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_off', related_query_name='time_off_entry', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', related_query_name='working_hour', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['user', 'date_start', 'date_end'], name='doctors_timeoff_range_idx'),
        ),
        migrations.AddIndex(
            model_name='workinghours',
            index=models.Index(fields=['user', 'weekday'], name='doctors_wh_by_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(fields=('user', 'weekday', 'start_time'), name='doctors_workinghours_unique_slot'),
        ),
    ]
