# Generated by Django 5.2.17 on 2026-09-29 09:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_timeoff_user_alter_workinghours_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproceduretype',
            name='price_per_surface',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Agar muolaja tish yuzalariga (MOD) bog'liq bo'lsa, har bir qo'shimcha yuza uchun qo'shiladigan narx.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Har bir qo'shimcha yuza narxi"),
        ),
        migrations.AddField(
            model_name='proceduretype',
            name='price_per_surface',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Agar muolaja tish yuzalariga (MOD) bog'liq bo'lsa, har bir qo'shimcha yuza uchun qo'shiladigan narx.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Har bir qo'shimcha yuza narxi"),
        ),
    ]
