# Generated by Django 5.0.9 on 2026-07-04 09:30

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('specialization', models.CharField(blank=True, default='', max_length=150, verbose_name='Mutaxassislik')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Biografiya')),
                ('commission_basis', models.CharField(choices=[('from_total', 'Umumiy narxdan'), ('from_net', 'Sof daromaddan (material chegirilgan)')], default='from_total', max_length=20, verbose_name='Komissiya asosi')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Standart komissiya foizi')),
                ('can_view_other_doctors', models.BooleanField(default=False, verbose_name="Boshqa shifokorlar ma'lumotini ko'ra oladi")),
                ('departments', models.ManyToManyField(blank=True, related_name='doctors', related_query_name='doctor', to='departments.department', verbose_name="Bo'limlar")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Shifokor profili',
                'verbose_name_plural': 'Shifokor profillari',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDoctorProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('specialization', models.CharField(blank=True, default='', max_length=150, verbose_name='Mutaxassislik')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Biografiya')),
                ('commission_basis', models.CharField(choices=[('from_total', 'Umumiy narxdan'), ('from_net', 'Sof daromaddan (material chegirilgan)')], default='from_total', max_length=20, verbose_name='Komissiya asosi')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Standart komissiya foizi')),
                ('can_view_other_doctors', models.BooleanField(default=False, verbose_name="Boshqa shifokorlar ma'lumotini ko'ra oladi")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'historical Shifokor profili',
                'verbose_name_plural': 'historical Shifokor profillari',
                'db_table': 'doctors_doctorprofile_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProcedureType',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('default_duration_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Standart davomiyligi (daqiqa)')),
                ('default_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Standart narx')),
                ('commission_rate_override', models.DecimalField(blank=True, decimal_places=2, help_text="Bo'sh qoldirilsa, shifokorning standart komissiya foizi ishlatiladi.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Komissiya foizi (override)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='procedure_type', to='departments.department', verbose_name="Bo'lim")),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Muolaja turi',
                'verbose_name_plural': 'historical Muolaja turlari',
                'db_table': 'doctors_proceduretype_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('default_duration_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Standart davomiyligi (daqiqa)')),
                ('default_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Standart narx')),
                ('commission_rate_override', models.DecimalField(blank=True, decimal_places=2, help_text="Bo'sh qoldirilsa, shifokorning standart komissiya foizi ishlatiladi.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Komissiya foizi (override)')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_types', related_query_name='procedure_type', to='departments.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Muolaja turi',
                'verbose_name_plural': 'Muolaja turlari',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('date_start', models.DateField(verbose_name='Boshlanish sanasi')),
                ('date_end', models.DateField(verbose_name='Tugash sanasi')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Sabab')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', related_query_name='time_off_entry', to='doctors.doctorprofile', verbose_name='Shifokor')),
            ],
            options={
                'verbose_name': 'Dam olish',
                'verbose_name_plural': 'Dam olish kunlari',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('weekday', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], verbose_name='Hafta kuni')),
                ('start_time', models.TimeField(verbose_name='Boshlanish')),
                ('end_time', models.TimeField(verbose_name='Tugash')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', related_query_name='working_hour', to='doctors.doctorprofile', verbose_name='Shifokor')),
            ],
            options={
                'verbose_name': 'Ish soati',
                'verbose_name_plural': 'Ish soatlari',
                'ordering': ['doctor__user__last_name', 'weekday', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['is_active'], name='doctors_active_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduretype',
            index=models.Index(fields=['department'], name='doctors_pt_dept_idx'),
        ),
        migrations.AddConstraint(
            model_name='proceduretype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('department', 'name'), name='doctors_proceduretype_dept_name_unique'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['doctor', 'date_start', 'date_end'], name='doctors_timeoff_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeoff',
            constraint=models.CheckConstraint(check=models.Q(('date_start__lte', models.F('date_end'))), name='doctors_timeoff_start_lte_end'),
        ),
        migrations.AddIndex(
            model_name='workinghours',
            index=models.Index(fields=['doctor', 'weekday'], name='doctors_wh_by_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(fields=('doctor', 'weekday', 'start_time'), name='doctors_workinghours_unique_slot'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='doctors_workinghours_start_before_end'),
        ),
    ]
