# Generated by Django 5.0.9 on 2026-07-04 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('type', models.CharField(choices=[('inventory.low_stock', 'Zaxira kam qoldi'), ('appointments.reminder_1d', 'Navbat eslatmasi (1 kun)'), ('appointments.reminder_2h', 'Navbat eslatmasi (2 soat)'), ('appointments.cancelled', 'Navbat bekor qilindi'), ('prescriptions.sent', 'Retsept yuborildi'), ('payments.received', "To'lov qabul qilindi"), ('patients.followup_invite', 'Profilaktik taklif'), ('patients.new', 'Yangi bemor'), ('ratings.milestone', 'Reyting yutugi'), ('generic', 'Umumiy')], default='generic', max_length=64, verbose_name='Turi')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('in_app', 'Ilova ichida'), ('sms', 'SMS')], default='telegram', max_length=20, verbose_name='Kanal')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborilgan'), ('failed', 'Xato')], default='pending', max_length=20, verbose_name='Holat')),
                ('context', models.JSONField(blank=True, default=dict, help_text="Xabarga tegishli qo'shimcha ma'lumot (material_id, appointment_id, ...).", verbose_name='Kontekst')),
                ('error_detail', models.TextField(blank=True, default='', verbose_name='Xato tafsiloti')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqti')),
                ('external_message_id', models.CharField(blank=True, default='', help_text='Masalan, Telegram ``message_id``.', max_length=128, verbose_name='Tashqi xabar ID')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_received', related_query_name='notification_received', to='patients.patient', verbose_name='Bemor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_received', related_query_name='notification_received', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi (xodim)')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='notif_status_idx'), models.Index(fields=['type'], name='notif_type_idx'), models.Index(fields=['user', '-created_at'], name='notif_user_idx'), models.Index(fields=['patient', '-created_at'], name='notif_patient_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('patient__isnull', False), _connector='OR'), name='notif_has_target'),
        ),
    ]
